name: GitHub Stats JSON Generator

on:
    schedule:
        - cron: "1 16 * * *"
    workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create stats directory
        run: mkdir -p json
        
      - name: Fetch GitHub stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/fetch-github-stats.mjs
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add json/qwqcode-repos.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats JSON" && git push)

permissions:
  contents: write
