on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        default: true
      cancel:
        description: 'Cancel'
        type: boolean
        default: false

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            skip: ${{ steps.data.outputs.skip }}
        steps:
            - 
                name: Check and cancel
                id: data
                run: |
                    if [ ${{ github.event.inputs.cancel }} == true ]; then
                        echo "skip=true" >> $GITHUB_OUTPUT
                    fi

    a:
        runs-on: ubuntu-latest
        needs: prepare
        if: ${{ needs.prepare.outputs.skip != 'true' }}
        steps:
            -
                name: print
                run: |
                    echo ${{ needs.check_cancel.outputs.result}}
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Made some changes in the code
                run: |
                    echo "Hello" > .github/workflows/abc.txt
            -
                name: Generate some files
                run: |
                    mkdir -p /tmp/builds
                    echo "Hello" > /tmp/builds/file1.txt
                    echo "World" > /tmp/builds/file2.txt
            -
                name: Upload files
                uses: actions/upload-artifact@v2
                with:
                    name: files
                    path: /tmp/builds
            -
                name: Upload files 2
                uses: actions/upload-artifact@v2
                with:
                    name: ui
                    path: .github/workflows
    b:
        runs-on: ubuntu-latest
        needs: a
        outputs:
            release_files: ${{ steps.print_files.outputs.release_files }}
        steps:
            -
                name: Download files
                uses: actions/download-artifact@v2
                with:
                    name: files
                    path: /tmp/builds
            -
                name: Download files 2
                uses: actions/download-artifact@v2
                with:
                    name: ui
                    path: .github/workflows
            -
                name: Print files
                id: print_files
                run: |
                    ls -l /tmp/builds
                    ls -l .github/workflows

                    RELEASE_FILES=$(find /tmp/builds -type f -exec readlink -f {} \;)

                    echo -e "release_files<<EOF" >> $GITHUB_OUTPUT
                    echo -e "$RELEASE_FILES" >> $GITHUB_OUTPUT
                    echo -e "EOF" >> $GITHUB_OUTPUT

    release:
        runs-on: ubuntu-latest
        needs: b
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2

            -
                name: Download files
                uses: actions/download-artifact@v2
                with:
                    name: files
                    path: /tmp/builds

            -
                name: Print files
                id: print_files
                run: |
                    echo -e "${{ needs.b.outputs.release_files }}"

            -
                name: Tag
                env:
                    GH_TOKEN: ${{ github.token }}
                run: |
                    git config user.name github-actions[bot]
                    git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        
                    gh release delete nightly --yes || true
                    git tag -d nightly || true
                    git push origin :refs/tags/nightly || true
        
                    git tag -f nightly
                    git push -f origin nightly

                    echo -e "test $(date +'%Y-%m-%d %H:%M:%S')\n123123" > release.txt
            -
                name: Release
                uses: softprops/action-gh-release@v2
                with:
                    draft: false
                    prerelease: true
                    name: 🧪 Nightly Version
                    tag_name: nightly
                    body_path: release.txt
                    files: |-
                        ${{ needs.b.outputs.release_files }}
